BEGIN;

DROP TABLE IF EXISTS user_answers;

DROP TABLE IF EXISTS answer_alternatives;

DROP TABLE IF EXISTS questions;

DROP TABLE IF EXISTS quizzes;

DROP TABLE IF EXISTS articles;

DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS user_role;

END;