version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT:-5432}:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER_ROOT}
      POSTGRES_PASSWORD: ${DB_PASSWORD_ROOT}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ:-Europe/Oslo}
    volumes:
      - db-data:/var/lib/postgresql/data
    profiles:
      - dev
      - prod

  bucket:
    image: quay.io/minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${BUCKET_USER_ROOT}
      MINIO_ROOT_PASSWORD: ${BUCKET_PASSWORD_ROOT}
      TZ: ${TZ:-Europe/Oslo}
    volumes:
      - bucket-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - dev
      - prod

  adminer:
    image: adminer
    restart: always
    environment:
      TZ: ${TZ:-Europe/Oslo}
    ports:
      - 8081:8080
    depends_on:
      - db
    profiles:
      - dev

  server:
    image: ghcr.io/molnes/nyhetsjeger:main
    restart: always
    env_file:
      - .env
    ports:
      - 8080:${PORT:-8080}
    environment:
      PORT: ${PORT:-8080}
      TZ: ${TZ:-Europe/Oslo}
    depends_on:
      - db
    volumes:
      - ./data/articles:/app/data/articles
    profiles:
      - prod

  caddy:
    image: caddy:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
      TZ: ${TZ:-Europe/Oslo}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server
    profiles:
      - prod

volumes:
  db-data:
    name: nyhetsjeger-postgres-data
  bucket-data:
    name: nyhetsjeger-bucket-data
  caddy_data:
  caddy_config:
