version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT:-5432}:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER_ROOT}
      POSTGRES_PASSWORD: ${DB_PASSWORD_ROOT}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    profiles:
      - dev
      - prod

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
    profiles:
      - dev

  server:
    image: ghcr.io/molnes/nyhetsjeger:main
    restart: always
    env_file:
      - .env
    ports:
      - 8080:${PORT:-8080}
    environment:
      PORT: ${PORT:-8080}
    depends_on:
      - db
    profiles:
      - prod

  caddy:
    image: caddy:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server
    profiles:
      - prod

volumes:
  db-data:
    name: nyhetsjeger-postgres-data
  caddy_data:
  caddy_config:
