services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
    profiles:
      - dev

  server:
    build: ./
    restart: always
    ports:
      - 8080:${PORT:-8080}
    environment:
      PORT: ${PORT:-8080}
    depends_on:
      - db
    profiles:
      - prod
