name: TestGo

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go mod download
      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest
      - name: Run templ
        run: templ generate -path ./internal/api/web/
      - name: Run unit tests
        run: go test ./...